#!/usr/bin/env bash

# Check if there are enough arguments
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY ADDITIONAL_VARIABLE"
elif [ "$#" -eq 4 ]; then
    scp -o StrictHostKeyChecking=no "$1" "$4@$2:~/"
else
    scp -o StrictHostKeyChecking=no -i "$5" "$1" "$4@$2:~/"
fi
