#!/usr/bin/env bash

# Check if there are enough arguments
case $# in
    [0-2])
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        ;;
    3)
        scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
        ;;
    *)
        scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
        ;;
esac
