#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
apt-get  update
apt-get  install nginx
echo "Hello World!" > /var/www/html/index.nginx-Nneka-Edeh.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/luischaparroc permanent;/" /etc/nginx/sites-available/default
service nginx start

